function(agnc_set_compiler_warnings target_name)
    if(MSVC)
        target_compile_options(${target_name} PRIVATE /W4 /permissive-)
        include(${CMAKE_SOURCE_DIR}/cmake/MsvcCompat.cmake)
        agnc_apply_msvc_compat(${target_name})
    else()
        target_compile_options(${target_name} PRIVATE -Wall -Wextra -Wpedantic)
    endif()
endfunction()
